package main

import "fmt"

// quick and dirty flutter code gen lol :P

var files = []string{
	"json/akaroa.json",
	"json/anawhata.json",
	"json/auckland.json",
	"json/ben_gunn_wharf.json",
	"json/bluff.json",
	"json/castlepoint.json",
	"json/deep_cove.json",
	"json/dunedin.json",
	"json/flour_cask_bay.json",
	"json/fresh_water_basin.json",
	"json/gisborne.json",
	"json/green_island.json",
	"json/havelock.json",
	"json/huruhi_harbour.json",
	"json/jackson_bay.json",
	"json/kaikoura.json",
	"json/kaingaroa.json",
	"json/kaiteriteri.json",
	"json/kaituna_river.json",
	"json/kawhia.json",
	"json/korotiti_bay.json",
	"json/leigh.json",
	"json/lottin_point_wakatiri.json",
	"json/lyttelton.json",
	"json/man_o_war_bay.json",
	"json/mana_marina.json",
	"json/mapua.json",
	"json/marsden_point.json",
	"json/matiatia_bay.json",
	"json/napier.json",
	"json/nelson.json",
	"json/north_cape_otou.json",
	"json/oamaru.json",
	"json/oban.json",
	"json/omokoroa.json",
	"json/onehunga.json",
	"json/opotiki_wharf.json",
	"json/opua.json",
	"json/owenga.json",
	"json/paratutae_island.json",
	"json/picton.json",
	"json/port_chalmers.json",
	"json/port_ohope_wharf.json",
	"json/port_taranaki.json",
	"json/pouto_point.json",
	"json/raglan.json",
	"json/rocky_point.json",
	"json/scott_base.json",
	"json/spit_wharf.json",
	"json/sumner.json",
	"json/tarakohe.json",
	"json/tauranga.json",
	"json/timaru.json",
	"json/waiorua_bay.json",
	"json/waitangi.json",
	"json/welcombe_bay.json",
	"json/wellington.json",
	"json/westport.json",
	"json/whakatane.json",
	"json/whanganui_river_entrance.json",
	"json/whangarei.json",
	"json/whangaroa.json",
	"json/whitianga.json",
}

var ports = []string{
	"Akaroa",
	"Anawhata",
	"Auckland",
	"Ben Gunn Wharf",
	"Bluff",
	"Castlepoint",
	"Deep Cove",
	"Dunedin",
	"Flour Cask Bay",
	"Fresh Water Basin",
	"Gisborne",
	"Green Island",
	"Havelock",
	"Huruhi Harbour",
	"Jackson Bay",
	"Kaikoura",
	"Kaingaroa",
	"Kaiteriteri",
	"Kaituna River",
	"Kawhia",
	"Korotiti Bay",
	"Leigh",
	"Lottin Point (Wakatiri)",
	"Lyttelton",
	"Mana Marina",
	"Man O' War Bay",
	"Mapua",
	"Marsden Point",
	"Matiatia Bay",
	"Napier",
	"Nelson",
	"North Cape (Otou)",
	"Oamaru",
	"Oban",
	"Omokoroa",
	"Onehunga",
	"Opotiki Wharf",
	"Opua",
	"Owenga",
	"Paratutae Island",
	"Picton",
	"Port Chalmers",
	"Port Ohope Wharf",
	"Port Taranaki",
	"Pouto Point",
	"Raglan",
	"Rocky Point",
	"Scott Base",
	"Spit Wharf",
	"Sumner",
	"Tarakohe",
	"Tauranga",
	"Timaru",
	"Waiorua Bay",
	"Waitangi",
	"Whanganui River Entrance",
	"Welcombe Bay",
	"Wellington",
	"Westport",
	"Whakatane",
	"Whangarei",
	"Whangaroa",
	"Whitianga",
}

func main() {
	for i, v := range ports {
		fmt.Printf("\"%s\": \"%s\",\n", v, files[i])
	}
}
